# Generated by Django 4.2.7 on 2023-11-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], max_length=50)),
            ],
        ),
    ]
